"""Banco de dados de jogos de horror e constantes do chatbot."""

JOGOS = {
    'resident evil': {
        'info': [
            'Resident Evil é um dos maiores clássicos do survival horror! Zumbis, Umbrella Corporation e muita tensão. 🧟',
            'A série RE mistura ação com terror. RE4 é considerado uma obra-prima!',
            'Do RE7 em diante, a série ganhou perspectiva em primeira pessoa, muito mais imersiva.',
        ],
        'genero': 'survival horror',
        'similares': ['dead space', 'dino crisis', 'evil within'],
        'tags': ['resident', 'biohazard', 're2', 're3', 're4', 're7', 're8', 'umbrella', 'zumbi'],
    },
    'silent hill': {
        'info': [
            'Silent Hill é referência em terror psicológico. A cidade reflete os medos dos personagens. 😰',
            'Silent Hill 2 é considerado um dos melhores jogos de horror de todos os tempos!',
            'O Pyramid Head é um dos vilões mais icônicos — representa culpa e punição.',
        ],
        'genero': 'terror psicológico',
        'similares': ['alan wake', 'amnesia', 'soma'],
        'tags': ['silent', 'hill', 'pyramid', 'head'],
    },
    'fnaf': {
        'info': [
            "Five Nights at Freddy's é focado em sobrevivência contra animatrônicos assassinos. 🤖",
            'FNAF é famoso pelos jump scares e uma lore extremamente complexa!',
            'São 9 jogos com uma história trágica por trás dos animatrônicos.',
        ],
        'genero': 'jump scare',
        'similares': ['outlast', 'bendy'],
        'tags': ['fnaf', 'freddy', 'animatronico', 'five', 'nights', 'bonnie', 'chica', 'foxy'],
    },
    'amnesia': {
        'info': [
            'Em Amnesia você não pode lutar — só fugir e se esconder! 😱',
            'Amnesia: The Dark Descent praticamente criou o gênero moderno de horror indie.',
            'A mecânica de sanidade torna o jogo ainda mais aterrorizante.',
        ],
        'genero': 'terror psicológico',
        'similares': ['soma', 'outlast', 'silent hill'],
        'tags': ['amnesia', 'descent', 'rebirth', 'sanidade'],
    },
    'alan wake': {
        'info': [
            'Alan Wake mistura terror psicológico com ação — luz contra a escuridão. 🔦',
            'A história envolve um escritor preso em um pesadelo sombrio e criativo.',
            'Alan Wake 2 expandiu o mistério de forma brilhante.',
        ],
        'genero': 'terror psicológico',
        'similares': ['silent hill', 'evil within', 'resident evil'],
        'tags': ['alan', 'wake', 'escritor'],
    },
    'dead space': {
        'info': [
            'Dead Space mistura terror com ficção científica no espaço. 🚀😱',
            'Os necromorfos são criaturas biomecânicas absolutamente horríveis.',
            'O remake trouxe uma experiência ainda mais imersiva e aterrorizante.',
        ],
        'genero': 'survival horror',
        'similares': ['resident evil', 'alien isolation', 'dino crisis'],
        'tags': ['necromorfo', 'necromorph'],
    },
    'outlast': {
        'info': [
            'Outlast é um jogo de fuga com câmera de visão noturna como única defesa. 📹',
            'O hospital psiquiátrico Mount Massive é absolutamente aterrorizante!',
            'Outlast 2 expande a experiência com cenários igualmente perturbadores.',
        ],
        'genero': 'survival',
        'similares': ['amnesia', 'alien isolation', 'soma'],
        'tags': ['outlast', 'hospital', 'whistleblower'],
    },
    'dino crisis': {
        'info': [
            'Dino Crisis é como Resident Evil, mas com dinossauros! 🦖',
            'Dinossauros geneticamente modificados com inteligência predatória.',
            'Um clássico subestimado que merece mais reconhecimento.',
        ],
        'genero': 'survival horror',
        'similares': ['resident evil', 'dead space'],
        'tags': ['dino', 'dinossauro'],
    },
    'evil within': {
        'info': [
            'The Evil Within traz terror intenso com criaturas bizarras. 😱',
            'Dirigido por Shinji Mikami, o criador de Resident Evil!',
            'O mundo distorcido do jogo é absolutamente perturbador.',
        ],
        'genero': 'survival horror',
        'similares': ['resident evil', 'silent hill'],
        'tags': ['within', 'shinji', 'mikami'],
    },
    'until dawn': {
        'info': [
            'Until Dawn é um jogo onde suas escolhas decidem quem vive ou morre. 🎬',
            'Quase um filme interativo de horror com atores reais.',
            'Cada decisão importa — qualquer personagem pode morrer.',
        ],
        'genero': 'narrativo',
        'similares': ['the quarry', 'bendy'],
        'tags': ['until', 'dawn'],
    },
    'the quarry': {
        'info': [
            'The Quarry segue o estilo Until Dawn — decisões que mudam tudo. 🎮',
            'Monitores num acampamento de verão... e coisas horríveis acontecem.',
            'Um dos melhores jogos de horror narrativo dos últimos anos.',
        ],
        'genero': 'narrativo',
        'similares': ['until dawn'],
        'tags': ['quarry', 'acampamento'],
    },
    'soma': {
        'info': [
            'SOMA é horror psicológico subaquático que questiona a existência humana. 🌊',
            'As criaturas desafiam sua percepção de realidade e consciência.',
            'Um dos jogos mais filosoficamente perturbadores que existem.',
        ],
        'genero': 'terror psicológico',
        'similares': ['amnesia', 'outlast'],
        'tags': ['soma', 'subaquatico', 'consciencia'],
    },
    'dead by daylight': {
        'info': [
            'Dead by Daylight: você caça... ou é caçado. 🩸',
            'Um jogador é o assassino, os outros tentam sobreviver e escapar.',
            'Cada assassino tem poderes únicos e mortais.',
        ],
        'genero': 'multiplayer',
        'similares': ['until dawn'],
        'tags': ['daylight', 'dbd', 'killer'],
    },
    'alien isolation': {
        'info': [
            'Alien: Isolation é tensão pura contra um Xenomorfo implacável. 👽',
            'O alien aprende com seus movimentos — cada partida é diferente.',
            'Esconder, distrair e economizar recursos: a chave da sobrevivência.',
        ],
        'genero': 'survival horror',
        'similares': ['dead space', 'outlast', 'soma'],
        'tags': ['alien', 'xenomorfo', 'ripley', 'sevastopol'],
    },
    'fatal frame': {
        'info': [
            'Fatal Frame: sua única arma é uma câmera contra espíritos. 📸',
            'A Camera Obscura captura fantasmas do folclore japonês.',
            'Quanto mais perto do espírito, mais dano... e mais medo.',
        ],
        'genero': 'terror psicológico',
        'similares': ['silent hill', 'haunting ground'],
        'tags': ['fatal', 'obscura'],
    },
    'haunting ground': {
        'info': [
            'Haunting Ground: terror psicológico onde você só foge e se esconde. 😨',
            'O pânico de Fiona afeta diretamente a jogabilidade.',
            'Clássico do PS2, pouco conhecido mas muito intenso.',
        ],
        'genero': 'terror psicológico',
        'similares': ['fatal frame', 'silent hill'],
        'tags': ['haunting', 'fiona'],
    },
    'bendy': {
        'info': [
            'Bendy and the Ink Machine: terror com estilo de cartoon antigo. 😈',
            'Um estúdio de animação abandonado cheio de segredos sombrios.',
            'Design artístico único que mistura nostalgia com horror.',
        ],
        'genero': 'ação + horror',
        'similares': ['fnaf', 'until dawn'],
        'tags': ['bendy', 'tinta', 'ink', 'machine', 'cartoon'],
    },
    'phasmophobia': {
        'info': [
            'Phasmophobia é um jogo de investigação paranormal cooperativo. Você e sua equipe entram em locais assombrados para identificar o tipo de fantasma. 👻',
            'Com mais de 24 tipos de fantasmas e ferramentas como EMF, termômetro e tábua ouija, cada partida é diferente!',
            'O jogo usa reconhecimento de voz — o fantasma pode ouvir você falando! Melhor ficar quieto quando ele ficar com raiva. 🎙️',
        ],
        'genero': 'multiplayer',
        'similares': ['dead by daylight', 'outlast'],
        'tags': ['phasmophobia', 'fantasma', 'paranormal', 'investigacao', 'emf', 'ouija'],
    },
    'layers of fear': {
        'info': [
            'Layers of Fear é um horror psicológico em primeira pessoa sobre um pintor perturbado obcecado com sua obra-prima. 🎨',
            'A mansão muda constantemente ao seu redor — corredores, portas e salas se transformam enquanto você explora.',
            'Layers of Fear 2 segue um ator em um navio abandonado, com atmosfera ainda mais surreal e perturbadora.',
        ],
        'genero': 'terror psicológico',
        'similares': ['amnesia', 'alan wake', 'silent hill'],
        'tags': ['layers', 'fear', 'pintor', 'mansao', 'obra'],
    },
    'little nightmares': {
        'info': [
            'Little Nightmares é um platformer sombrio onde você foge de criaturas grotescas numa instalação subaquática chamada The Maw. 🕯️',
            'O design artístico é único — tudo é enorme e ameaçador comparado à pequena protagonista Six.',
            'Little Nightmares 2 expande o mundo com Mono e Six fugindo de uma cidade perturbadora dominada por sinais de TV.',
        ],
        'genero': 'terror psicológico',
        'similares': ['soma', 'bendy', 'haunting ground'],
        'tags': ['little', 'nightmares', 'six', 'maw', 'mono', 'pesadelo'],
    },

}

# Nomes alternativos para jogos (alias → chave em JOGOS)
NOMES_ALT = {
    'five nights at freddy': 'fnaf',
    'five nights': 'fnaf',
    'biohazard': 'resident evil',
    're village': 'resident evil',
    'phasm': 'phasmophobia',
    'phasmo': 'phasmophobia',
    'layers': 'layers of fear',
    'little nightmares 2': 'little nightmares',
    'ln2': 'little nightmares',
    'ln1': 'little nightmares',
}

GENEROS = {
    'survival horror': ['Resident Evil', 'Dead Space', 'Dino Crisis', 'Evil Within', 'Alien Isolation'],
    'terror psicológico': ['Silent Hill', 'Amnesia', 'SOMA', 'Alan Wake', 'Fatal Frame', 'Haunting Ground',  'Layers of Fear', 'Little Nightmares'],
    'jump scare': ['FNAF', 'Outlast', 'Bendy'],
    'ação': ['Resident Evil', 'Dead Space', 'Alan Wake', 'Evil Within'],
    'narrativo': ['Until Dawn', 'The Quarry'],
    'multiplayer': ['Dead by Daylight', 'Phasmophobia'],
    'ficção científica': ['Dead Space', 'Alien Isolation', 'SOMA'],
}

SIM = {'sim', 'ss', 'claro', 'certeza', 'obvio', 'demais', 'bora', 'quero',
       'show', 'massa', 'top', 'yes', 'adoro', 'gosto', 'curto', 'amo',
       'joguei', 'conheco', 'manda', 'pode', 'dale', 'vamos', 's', 'sip',
       'aham', 'uhum', 'yeah', 'siiim', 'siim', 'isso', 'ja', 'com certeza'}

NAO = {'nao', 'não', 'nope', 'nunca', 'nem', 'negativo', 'passo', 'nah',
       'n', 'nn', 'nada', 'naoo', 'nop'}

# ================================================================
# PERGUNTAS PROFUNDAS — Conversa interativa por jogo
# Cada entry: (pergunta do bot, respostas para sim, respostas para não)
# ================================================================

CONVERSA_PROFUNDA = {
    'resident evil': [
        ("Você já jogou o Resident Evil 1, o clássico que começou tudo? 🏚️",
         "A mansão Spencer é icônica! Aqueles puzzles e corredores escuros marcaram uma geração. Sabia que o jogo quase foi cancelado?",
         "Vale muito a pena! É o começo de tudo — sobreviver na mansão Spencer com recursos limitados é uma experiência única."),
        ("Curte mais o estilo clássico (câmera fixa) ou o moderno (primeira/terceira pessoa)?",
         "O estilo clássico tem um charme especial! A câmera fixa criava uma tensão absurda porque você nunca sabia o que vinha pela frente.",
         "O estilo moderno é mais imersivo mesmo! RE4 revolucionou com a câmera sobre o ombro, e RE7/RE8 em primeira pessoa são de arrepiar."),
        ("RE4 é considerado uma obra-prima. Você já jogou? 🎮",
         "RE4 mudou o gênero inteiro! A aldeia, os Ganados, o Krauser... e o modo Mercenaries é viciante demais!",
         "RE4 é obrigatório! Mistura ação com tensão perfeitamente. O remake de 2023 ficou incrível, recomendo começar por ele."),
        ("E o RE2 Remake? Muita gente considera o melhor remake já feito!",
         "O Mr. X te perseguindo pelos corredores é de gelar o sangue! A delegacia de Raccoon City nunca foi tão aterrorizante. 😱",
         "O RE2 Remake é sensacional! Te coloca na pele de Leon ou Claire na delegacia infestada de zumbis. Imperdível!"),
        ("Você conhece a história da Umbrella Corporation? 🧬",
         "A Umbrella é uma das vilãs mais icônicas dos games! O T-Virus, o G-Virus, os experimentos... cada jogo revela mais da conspiração.",
         "A Umbrella é a empresa farmacêutica que criou o T-Virus e causou o apocalipse zumbi. A trama dela conecta TODOS os jogos da série!"),
        ("RE7 mudou tudo com a primeira pessoa. Curtiu essa mudança?",
         "A família Baker é assustadora demais! Jack te perseguindo é puro terror. E a conexão com a saga principal surpreendeu todo mundo.",
         "Muita gente estranhou no começo, mas RE7 salvou a série! É muito mais imersivo e a família Baker é inesquecível. Recomendo!"),
        ("Village (RE8) com a Lady Dimitrescu... jogou? 🧛‍♀️",
         "O castelo Dimitrescu é lindo e aterrorizante ao mesmo tempo! E a parte do Beneviento... aquela casa de bonecas é perturbadora demais.",
         "RE8 mistura vários tipos de horror: vampiros, lobisomens, bonecas... a Lady Dimitrescu virou um ícone instantâneo da franquia!"),
        ("Qual vilão de RE te assusta mais? Nemesis, Mr. X, Jack Baker? 😈",
         "Boa escolha! Os stalkers de RE são únicos — cada um cria um tipo diferente de tensão. Nemesis gritando 'STARS' é traumático!",
         "Todos são assustadores de formas diferentes! Nemesis é implacável, Mr. X é silencioso e opressor, Jack Baker é insano."),
        ("Sabia que RE tem filmes, séries e até animações? Já viu algum?",
         "Os filmes são polêmicos entre os fãs, mas as animações como Degeneration e Damnation são bem fiéis ao jogo!",
         "Tem os filmes live-action da Milla Jovovich, a série da Netflix, e animações em CGI. As animações são as mais fiéis aos games!"),
        ("Se pudesse escolher UM RE pra jogar pela primeira vez de novo, qual seria?",
         "Escolha difícil! Cada um tem seu brilho. RE2 Remake pela perfeição, RE4 pela diversão, RE7 pelo terror puro... todos são memoráveis! 🎮",
         "Eu recomendaria RE2 Remake pra quem quer terror, RE4 pra quem quer ação, ou RE7 pra quem quer se borrar de medo! 😱"),
    ],
    'silent hill': [
        ("Você já jogou Silent Hill 2? É considerado o auge do terror psicológico! 😰",
         "SH2 é uma obra de arte! A história de James e Maria é devastadora. O final te faz repensar TUDO que aconteceu no jogo.",
         "SH2 é obrigatório pra quem curte terror! A história de James buscando sua esposa morta em Silent Hill é profundamente perturbadora."),
        ("O Pyramid Head te assusta? Ele é um dos vilões mais icônicos do horror! 🔺",
         "Pyramid Head é genial porque ele não é só um monstro — ele representa a culpa e o desejo de punição. Puro terror psicológico!",
         "Mesmo sem jogar, Pyramid Head é cultural! Ele aparece arrastando aquela espada gigante e simboliza os demônios internos dos personagens."),
        ("Prefere o terror psicológico de SH ou o mais ação de outros jogos?",
         "SH é mestre em mexer com sua mente! A neblina, os sons, nunca saber se o que você vê é real... é uma experiência diferente de tudo.",
         "Muita gente prefere ação, e tá tudo bem! Mas SH prova que o medo mais forte vem de dentro, não de monstros que você pode matar."),
        ("A trilha sonora do Akira Yamaoka é lendária. Já ouviu? 🎵",
         "Yamaoka é um gênio! Mistura industrial, rock e ambient de um jeito que só Silent Hill tem. 'Theme of Laura' é de chorar!",
         "Procura no YouTube! A trilha do SH é considerada uma das melhores de todos os games. Funciona até fora do jogo, é linda e assustadora."),
        ("Sabia que a cidade de Silent Hill reflete os medos de cada personagem?",
         "É o que torna SH tão especial! Cada personagem vê uma Silent Hill diferente, moldada pelos seus traumas. O mapa muda com a psique!",
         "É fascinante! A cidade é uma entidade que manifesta os medos de quem entra. Por isso os monstros de cada jogo são únicos pro personagem."),
        ("SH1 no PS1 e SH3 são muito subestimados. Conhece? 🎮",
         "SH1 é o original que criou tudo — Alessa, a seita, o fog! E SH3 continua a história com Heather de forma brilhante.",
         "SH1 começou tudo com a história de Harry buscando sua filha. SH3 traz Heather, filha de Harry, e fecha o arco de forma incrível!"),
        ("O que te assusta mais: monstros ou o silêncio de SH?",
         "O silêncio é arma poderosa em SH! Quando o rádio para de fazer estática, você SABE que algo vai acontecer... e a espera é o pior.",
         "Os dois funcionam juntos! Os monstros simbolizam traumas, e o silêncio te prepara psicologicamente pro horror. Genialidade pura."),
        ("Você joga no escuro com fone? É a forma definitiva de jogar SH! 🎧",
         "Corajoso! SH no escuro com fone é uma experiência que marca pra vida. Cada som, cada passo, cada estática do rádio fica 10x mais intenso!",
         "Se um dia tiver coragem, tenta! O design de som do SH foi feito pra fones. Muda completamente a experiência de terror."),
        ("O remake de SH2 pela Bloober Team... o que acha?",
         "Reimaginar SH2 é uma responsabilidade enorme! Os fãs tinham expectativas altíssimas. É interessante ver como uma obra-prima é reinterpretada.",
         "Independente do remake, o SH2 original sempre vai ser especial. Mas é bom ver a franquia recebendo atenção de novo!"),
        ("Se Silent Hill fosse real, você entraria na neblina? 🌫️",
         "Corajoso! Lembre-se: a cidade mostra seus piores medos. O que apareceria pra você? Esse é o verdadeiro terror de Silent Hill!",
         "Sábia decisão! 😂 Ninguém sano entraria naquela neblina. Mas é isso que torna SH tão fascinante — o horror de enfrentar a si mesmo."),
    ],
    'alan wake': [
        ("Você já jogou Alan Wake 1? A história do escritor preso no pesadelo é incrível! 🔦",
         "AW1 é genial! A mecânica de luz contra escuridão é única. E a narrativa em formato de série de TV é muito criativa!",
         "AW1 é uma experiência única! Você é um escritor cuja história de terror se torna realidade. A mecânica de usar luz como arma é brilhante."),
        ("A mecânica de usar luz pra derrotar inimigos te agrada? 🔦",
         "É uma das mecânicas mais criativas do horror! Lanterna + flare gun + holofotes criam um gameplay totalmente diferente.",
         "É bem diferente do usual! Em vez de só atirar, você precisa 'descascar' a escuridão dos inimigos com luz antes de poder derrotá-los."),
        ("Alan Wake tem uma pegada muito de Stephen King. Curte esse estilo? 📖",
         "A influência é clara! Cidade pequena, escritor, forças sobrenaturais... é como jogar um livro do King. A atmosfera de Bright Falls é perfeita!",
         "O jogo é inspirado em Stephen King e Twin Peaks! Bright Falls é uma cidadezinha americana com segredos sombrios. Clima de thriller literário!"),
        ("A série foi feita em formato de episódios de TV. Curtiu essa estrutura?",
         "Cada episódio termina com um cliffhanger e a tela 'Previously on Alan Wake'! É como maratonar uma série de terror. Super criativo!",
         "É bem diferente! Cada capítulo funciona como um episódio, com resumo do anterior e trilha sonora no final. Dá vontade de jogar mais!"),
        ("Alan Wake 2 veio depois de 13 anos. Já jogou? 😱",
         "A espera valeu! AW2 é mais sombrio, mais complexo, e a adição da agente Saga Anderson trouxe uma perspectiva nova incrível!",
         "AW2 finalmente saiu em 2023! É mais terror psicológico que o primeiro, com gráficos absurdos e narrativa dupla entre Alan e Saga."),
        ("Sabia que Alan Wake se conecta com Control, outro jogo da Remedy?",
         "O Remedy Connected Universe é fascinante! O DLC de Control 'AWE' conecta os dois jogos. A Remedy está criando seu próprio multiverso!",
         "A Remedy criou um universo compartilhado! Alan Wake e Control existem no mesmo mundo. O DLC 'AWE' de Control traz o Alan diretamente."),
        ("O que te assusta mais em AW: os Taken ou a própria escuridão? 🌑",
         "A escuridão em AW não é só ausência de luz — é uma ENTIDADE. Os Taken são pessoas consumidas por ela. O conceito é aterrorizante!",
         "Os dois funcionam juntos! A Dark Presence é uma força que consome pessoas, transformando-as em Taken. A floresta à noite é opressiva."),
        ("Bright Falls e Cauldron Lake... a ambientação te agrada?",
         "A ambientação pacífica do noroeste americano em contraste com o horror é genial! De dia tudo parece tranquilo, de noite é pesadelo!",
         "O cenário é lindo e sinistro! Floresta densa, lagos escuros, uma cidadezinha isolada... perfeito pra uma história de terror."),
        ("AW tem umas músicas épicas, como 'War' do Poets of the Fall. Ouviu? 🎵",
         "A cena do 'War' na fazenda de Barry com o palco de rock é LENDÁRIA! E 'The Poet and the Muse' do Old Gods of Asgard é parte da lore!",
         "Procura 'Alan Wake War scene' no YouTube! É uma das cenas mais icônicas de um jogo. Música e gameplay juntos de forma épica!"),
        ("Se você fosse escritor como Alan, teria coragem de usar o manuscrito? ✍️",
         "O dilema do Alan é fascinante: tudo que ele escreve se torna real, mas ele não pode controlar como! Seria tentador e aterrorizante!",
         "Sábia escolha! O manuscrito é uma bênção e maldição. Tudo que Alan escreve acontece, mas de formas distorcidas e sombrias. Melhor não arriscar! 😅"),
    ],
    'fnaf': [
        ("Você conhece a lore do FNAF? É uma das histórias mais complexas dos jogos! 🤖",
         "A lore é genial! William Afton, o Purple Guy, e as almas das crianças presas nos animatrônicos formam uma tragédia sombria incrível.",
         "A lore vai muito além dos jump scares! Envolve assassinatos, almas presas, experimentos e uma família marcada pela maldade de William Afton."),
        ("O primeiro jogo, guardando a noite de 12h às 6h... já jogou? 😰",
         "Aquela tensão de gerenciar energia enquanto verifica as câmeras é viciante! A primeira vez que o Bonnie aparece na porta é traumatizante.",
         "É simples mas genial! Você só observa câmeras e fecha portas, mas a tensão de ficar sem energia às 5h da manhã é de enlouquecer."),
        ("Qual animatrônico te assusta mais? Freddy, Bonnie, Chica ou Foxy? 🦊",
         "Boa escolha! Cada animatrônico tem seu comportamento único. O Foxy é especialmente traiçoeiro — você precisa ficar de olho na Pirate Cove!",
         "Todos são aterrorizantes de formas diferentes! Foxy corre pelo corredor, Freddy apaga as luzes, Bonnie aparece do nada... 😱"),
        ("FNAF tem uma quantidade enorme de jogos e spin-offs. Conhece todos?",
         "A franquia cresceu muito! De FNAF 1 a Security Breach, passando por Sister Location e Pizzeria Simulator, cada jogo expande a lore.",
         "Existem mais de 9 jogos principais e vários spin-offs! Sister Location e Pizzeria Simulator são essenciais para entender a história completa."),
        ("A teoria das almas das crianças nos animatrônicos... o que acha?",
         "É a espinha dorsal de tudo! William Afton matou crianças e suas almas ficaram presas nos animatrônicos, buscando vingança. Perturbador e trágico!",
         "É uma das teorias mais sombrias dos games! Crianças assassinadas cujas almas animam os robôs e perseguem o guarda noturno inocente."),
        ("Você sabia que tem um filme do FNAF? Assistiu? 🎬",
         "O filme foi muito aguardado pelos fãs! Ver o Freddy Fazbear's Pizza na tela grande foi um sonho realizado pra muita gente.",
         "O filme de 2023 trouxe a história pra tela grande! Segue um segurança noturno descobrindo os segredos sombrios da pizzaria."),
        ("Security Breach é o mais recente e tem mundo aberto. Jogou?",
         "O Glamrock Freddy sendo aliado do jogador foi uma virada incrível! E o Pizzaplex é enorme, cheio de segredos e rotas alternativas.",
         "Security Breach mudou a fórmula! Em vez de ficar parado numa sala, você explora um shopping enorme fugindo dos animatrônicos Glamrock."),
        ("A música 'It's Me' e os easter eggs escondidos... você caça essas coisas?",
         "Os easter eggs do FNAF são lendários! O criador Scott Cawthon escondia pistas da lore em lugares absurdos. A comunidade ficou anos decifrando!",
         "Vale muito a pena explorar! A comunidade do FNAF é das mais dedicadas em caçar segredos. Cada jogo tem mensagens ocultas e mini-games reveladores."),
    ],
 
    'dead space': [
        ("Você já jogou Dead Space 1, o original de 2008? É um clássico absoluto! 🚀",
         "A USG Ishimura é um dos cenários mais aterrorizantes dos games! Aquele silêncio do espaço com os sons dos necromorfos é de enlouquecer.",
         "DS1 é onde tudo começa! Isaac Clarke chega numa nave espacial abandonada e encontra uma infestação de necromorfos. É terror espacial no seu melhor."),
        ("A mecânica de desmembrar necromorfos é única. O que acha dela?",
         "Brilhante! Em vez de atirar na cabeça como zumbi normal, você precisa cortar os membros dos necromorfos. Muda completamente a estratégia!",
         "É uma das mecânicas mais criativas do horror! Atirar no corpo não adianta — você precisa cortar braços, pernas e tentáculos para sobreviver."),
        ("Isaac Clarke é mudo no DS1 mas fala no DS2. Preferiu qual versão?",
         "O Isaac mudo deixa tudo mais imersivo — você SE TORNA ele. Mas no DS2 ele ganhou personalidade e a história ficou mais envolvente emocionalmente.",
         "Isaac mudo no DS1 cria uma experiência mais imersiva, como se você fosse o personagem. No DS2 ele tem voz e a história fica mais pessoal."),
        ("O Marker e o culto Unitologist... entendeu a história toda? 🔺",
         "A lore do Dead Space é profunda! O Marker é um artefato alienígena que induz loucura e cria necromorfos. A Unitology é uma seita que o adora!",
         "É bem elaborada! O Marker é um obelisco alienígena que corrompe mentes e transforma corpos em necromorfos. A Unitology acredita ser sagrado."),
        ("Dead Space 2 é considerado por muitos o melhor da trilogia. Concorda?",
         "DS2 aprimorou tudo! Isaac mais caracterizado, ambientações mais variadas com a Sprawl, e cenas de tensão absurdas como a do olho.",
         "DS2 é incrível! A cena do olho é uma das mais tensas já feitas num game. A Sprawl como cenário trouxe variedade à experiência."),
        ("O Remake de 2023 ficou espetacular. Já jogou? 😱",
         "O remake elevou tudo! Gráficos fotorrealistas, trilha sonora remasterizada e novos segredos que expandem a lore original. Vale muito!",
         "O remake de 2023 é visualmente deslumbrante! Mantém a essência do original mas adiciona detalhes de lore e melhorias de gameplay significativas."),
        ("Qual necromorfo te apavora mais? O Slasher, o Lurker ou o Exploser?",
         "Boa escolha! Cada necromorfo foi design pra criar um tipo diferente de pânico. O Exploser é uma armadilha andando, o Lurker embosca de longe...",
         "Todos são horríveis por razões diferentes! Slashers são rápidos, Lurkers atiram de longe, e o Exploser... bem, o nome já diz tudo. 💥"),
        ("Dead Space tem logs de áudio que constroem o horror antes de você ver. Ouviu todos?",
         "Os logs são geniais! Eles constroem o horror gradualmente — ouvir os tripulantes enlouquecendo antes de encontrar os necromorfos é perturbador.",
         "Vale muito a pena ouvir! Os logs de áudio contam o que aconteceu na Ishimura antes de Isaac chegar. É storytelling ambiental de alto nível."),
    ],
 
    'amnesia': [
        ("Você já jogou Amnesia: The Dark Descent? É o terror que não te deixa lutar! 😱",
         "The Dark Descent é uma obra-prima! Sem armas, sem combate — só se esconder e rezar enquanto o monstro passa. A mecânica de sanidade é genial.",
         "A premissa é aterrorizante! Você está num castelo escuro sem memória e sem armas. Se olhar muito para os monstros, vai enlouquecer. 😰"),
        ("A mecânica de sanidade te incomoda no jogo? Quanto mais vê o monstro, mais insano fica!",
         "É brilhante! Você precisa ficar no escuro pra se esconder, mas ficar no escuro também diminui a sanidade. Um dilema perfeito!",
         "É desconfortável no melhor sentido! Fica no escuro e enlouquece, fica na luz e o monstro te acha. Não tem saída confortável. Terror puro."),
        ("Já se escondeu num armário enquanto o monstro procurava por você? 🚪",
         "Uma das experiências mais tensas dos games! Ouvir o Grunt rondando do lado de fora enquanto você torce pra ele ir embora é agonizante.",
         "Essa é A experiência do Amnesia! Entrar num armário, fechar a porta e ouvir os passos pesados do Grunt passando. O coração dispara mesmo!"),
        ("O castelo Brennenburg tem uma atmosfera única. A ambientação te agradou?",
         "O castelo é opressor de um jeito especial! Cada sala parece guardar um segredo sombrio, e os documentos espalhados contam uma história perturbadora.",
         "É um dos cenários mais bem construídos do horror! Porões alagados, masmorras, laboratórios medievais... cada área tem sua própria identidade de terror."),
        ("Amnesia: Rebirth é a continuação. Já jogou? O ambiente mudou para o deserto!",
         "Rebirth é perturbador de um jeito diferente! Trocou o castelo pelo deserto e cavernas, e a mecânica de ansiedade substituiu a de sanidade.",
         "Rebirth saiu em 2020 e expandiu o universo! Você joga como Tasi Trianon sobrevivendo no deserto após um acidente. Diferente mas igualmente tenso."),
        ("Amnesia: The Bunker é o mais recente, com gerador de luz aleatório. Conhece?",
         "The Bunker mudou a fórmula! Agora há um monstro gerado aleatoriamente que reage a sons. Cada partida é diferente e o fator surpresa é real!",
         "The Bunker de 2023 é inovador! Um bunker da Primeira Guerra Mundial, um monstro único que reage a sons e um gerador que pode acabar. Terror imprevisível!"),
        ("Os documentos e diários espalhados constroem a história. Você lê todos?",
         "Os documentos são essenciais! Eles revelam o passado de Daniel, os experimentos de Alexander e a história sombria do castelo. Lore riquíssima!",
         "Vale muito ler! A história de Daniel descobrindo as atrocidades cometidas em Brennenburg é tão perturbadora quanto os monstros. Às vezes mais."),
        ("Se você não pudesse lutar num jogo de terror, conseguiria jogar? 😰",
         "Essa é a genialidade do Amnesia! Tirar o combate força você a sentir vulnerabilidade de verdade. É o terror mais honesto que existe num game.",
         "Muita gente não consegue! Sem armas, sem defesa, só esconde e corre. Mas é exatamente isso que torna o medo em Amnesia completamente real."),
    ],

    'phasmophobia': [
        ("Você já jogou Phasmophobia com amigos? A experiência cooperativa é insana! 👻",
         "Jogar com amigos é o melhor! A comunicação é essencial — e o pânico quando alguém grita 'HUNTING!' é impagável.",
         "Recomendo muito experimentar com amigos! Investigar fantasmas em grupo cria momentos de terror e risada que nenhum jogo solo consegue."),
        ("O fato do fantasma ouvir sua voz pelo microfone te assusta? 🎙️",
         "O reconhecimento de voz é genial! Falar o nome do fantasma pode irritá-lo e iniciar uma caçada. Muita gente joga no mudo de tanto medo!",
         "É uma mecânica única! O jogo capta sua voz real e o fantasma reage. Falar alto ou provocar pode ser fatal — literalmente."),
        ("Qual ferramenta de investigação você mais usa? EMF, Spirit Box, termômetro? 🔦",
         "Cada ferramenta tem seu charme! O Spirit Box é tenso porque você ouve o fantasma responder, e o DOTS mostra a silhueta dele passando. Arrepiante!",
         "As ferramentas são parte central do jogo! EMF detecta atividade, Spirit Box permite falar com o fantasma, e o termômetro mostra quedas de temperatura assustadoras."),
        ("Já conseguiu identificar um Revenant ou um Demônio? São os mais perigosos! 😈",
         "Esses são de gelar o sangue! O Revenant é absurdamente rápido quando te vê, e o Demônio inicia caçadas com muito mais frequência. Puro caos!",
         "São os fantasmas mais temidos! O Revenant corre muito rápido atrás de você, e o Demônio caça com pouquíssima provocação. Jogadores experientes tremem!"),
        ("A tábua Ouija e o Music Box são itens amaldiçoados. Já usou algum? 🕯️",
         "Os itens amaldiçoados são risco puro! A Ouija pode revelar onde o fantasma está, mas cada pergunta drena sua sanidade. O Music Box atrai o fantasma... perigosamente perto.",
         "São itens arriscados mas úteis! A tábua Ouija responde perguntas sobre o fantasma, e o Music Box o faz aparecer. Usar ou não é sempre uma decisão tensa."),
        ("Phasmophobia atualiza sempre com novos fantasmas e mapas. Acompanha as atualizações?",
         "As atualizações são incríveis! Novos fantasmas mudam completamente a estratégia. O Thaye que envelhece, o Moroi que amaldiçoa... cada um é único!",
         "O jogo evolui constantemente! Novos tipos de fantasma, mapas maiores e mecânicas são adicionados. A comunidade é muito ativa e dedicada."),
        ("Qual mapa te assusta mais? A escola, o asilo ou a fazenda? 🏚️",
         "Cada mapa tem seu terror! O asilo é enorme e fácil de se perder, a fazenda é claustrofóbica, e a escola tem corredores longos e escuros.",
         "Os mapas variam muito! Mapas pequenos são intensos porque o fantasma está sempre perto. Mapas grandes como o asilo são tensos porque você fica sozinho e vulnerável."),
        ("Se tivesse que investigar um fantasma real com as ferramentas do jogo, teria coragem? 😱",
         "Corajoso! Na vida real seria muito mais aterrorizante — sem respawn! Mas a ideia de usar EMF e Spirit Box num local assombrado é fascinante.",
         "Sábia decisão! 😂 No jogo já é tenso o suficiente. Na vida real, sem a opção de fechar o jogo, seria apavorante demais!"),
    ],

    'layers of fear': [
        ("Você já jogou o primeiro Layers of Fear? A mansão que muda é perturbadora! 🎨",
         "A mansão mutante é genial! Você vira de costas e o corredor já é outro. Nunca dá pra confiar no ambiente — é desorientador e aterrorizante.",
         "A premissa é única! Você é um pintor obcecado com sua obra-prima, e a mansão se distorce ao seu redor refletindo sua loucura. Terror psicológico puro."),
        ("A história do pintor e sua obsessão pela obra-prima te tocou? 🖌️",
         "É uma história trágica! A obsessão dele destruiu sua família e sua mente. Cada cômodo da mansão revela mais da sua queda. Arte e horror juntos.",
         "É bem profunda! O pintor sacrificou tudo — família, sanidade, humanidade — pela pintura perfeita. O jogo mostra como a obsessão pode consumir alguém."),
        ("As portas e corredores que mudam quando você não está olhando... isso te incomoda?",
         "É uma das mecânicas mais criativas do terror! Você entra num corredor, olha pra trás e ele desapareceu. O jogo brinca com sua percepção constantemente.",
         "Essa mecânica é o coração do jogo! Nada é confiável — paredes movem, portas somem, cômodos se transformam. Você nunca sabe onde realmente está."),
        ("Layers of Fear 2 se passa num navio com um ator. Conhece? 🚢",
         "LoF2 é ainda mais surreal! O cenário de navio abandonado com referências cinematográficas cria uma atmosfera única. O diretor misterioso é perturbador.",
         "O segundo jogo muda o cenário pra um navio e o protagonista pra um ator. As referências a filmes clássicos e o tom mais surreal o tornam bem diferente do primeiro."),
        ("O estilo artístico do jogo é muito expressionista. Isso agrega ao terror pra você?",
         "Totalmente! As pinturas distorcidas, as cores saturadas e as formas grotescas criam um terror visual único. É como estar dentro de um quadro perturbador.",
         "O visual é parte essencial! Inspirado em expressionismo e arte perturbadora, cada cena parece uma pintura de pesadelo. Poucos jogos usam arte tão bem pro horror."),
        ("Layers of Fear (2023) unificou os dois jogos. Já experimentou? 🎮",
         "A versão unificada em Unreal Engine 5 ficou linda! Ter os dois jogos conectados com gráficos atualizados e conteúdo novo valorizou muito a experiência.",
         "Em 2023 saiu uma versão que combina LoF1 e LoF2 com gráficos novos em UE5 e conteúdo adicional. É a forma definitiva de experimentar a série!"),
        ("O que te assusta mais: jump scares ou a loucura gradual do personagem? 🧠",
         "A loucura gradual é mais eficaz! Os jump scares funcionam no momento, mas perceber que o personagem — e talvez você — está perdendo a sanidade é perturbador de verdade.",
         "Os dois têm seu papel! Layers of Fear usa jump scares com moderação, mas o verdadeiro horror vem de sentir o ambiente e a mente do protagonista se deteriorando."),
        ("Se você fosse o pintor, sacrificaria tudo pela obra perfeita? ✍️",
         "Pergunta difícil! A arte tem esse poder de consumir. O jogo mostra que a linha entre dedicação e obsessão é tênue — e cruzá-la tem consequências terríveis.",
         "Sábia escolha! O jogo é um alerta sobre obsessão. A obra-prima nunca é alcançada porque o preço é sempre maior. Melhor criar com equilíbrio! 😅"),
    ],

    'little nightmares': [
        ("Você já jogou o primeiro Little Nightmares? The Maw é um cenário inesquecível! 🕯️",
         "The Maw é brilhante! Uma instalação subaquática gigante e grotesca onde tudo é enorme e ameaçador. A escala faz você sentir a vulnerabilidade da Six.",
         "Little Nightmares 1 se passa em The Maw, uma instalação misteriosa. Você joga como Six, uma criança minúscula fugindo de criaturas monstruosas. Visual incrível!"),
        ("Os vilões como o Chef e a Lady são bem perturbadores. Qual te assusta mais? 😰",
         "Cada vilão é assustador de um jeito! O Chef com aqueles braços longos cortando carne, e a Lady com sua máscara e vaidade mortal. Design impecável!",
         "São criaturas grotescas e memoráveis! O Chef persegue você pela cozinha, e a Lady governa The Maw com poderes misteriosos. Cada encontro é tenso."),
        ("O fato de Six ser uma criança tão pequena num mundo gigante te impacta?",
         "É o que torna o jogo tão especial! A escala exagerada faz cada mesa, cada cadeira e cada inimigo parecer gigantesco e opressor. Você se sente indefeso.",
         "Essa é a essência do jogo! Tudo é desproporcional — portas enormes, criaturas gigantes. Simula a perspectiva de uma criança num mundo assustador de adultos."),
        ("Little Nightmares 2 com Mono e a cidade distorcida... jogou? 📺",
         "LN2 é incrível! A cidade dominada por sinais de TV, os inimigos com pescoços tortos, e a relação Mono-Six criam algo especial. O final é devastador!",
         "O segundo jogo expande o mundo! Mono e Six atravessam uma cidade perturbadora onde todos estão hipnotizados por televisões. O design e a história são maiores."),
        ("O final de LN2 te surpreendeu? A revelação sobre Mono é de cair o queixo! 😱",
         "O twist é devastador! Descobrir a conexão entre Mono e o Homem Magro cria um loop temporal trágico. E a traição de Six... dói até agora.",
         "Sem spoilers pesados, mas o final muda completamente sua perspectiva sobre a história. É um dos twists mais impactantes dos jogos indie recentes."),
        ("O design artístico de Little Nightmares é único. A estética te agrada? 🎨",
         "O visual é deslumbrante! Estilo quase stop-motion, cores apagadas, proporções distorcidas. Cada cenário parece um pesadelo infantil materializado.",
         "O estilo visual é uma marca registrada! Inspirado em animação stop-motion e arte surrealista, cria um mundo que parece um sonho ruim de criança. Lindo e assustador."),
        ("A fome de Six é um tema recorrente e perturbador. O que acha dessa mecânica? 🍽️",
         "A fome de Six é simbólica e perturbadora! A cada capítulo ela come algo pior, e no final... bom, a revelação sobre o que ela realmente é muda tudo.",
         "A fome é central na história! Six precisa comer em momentos específicos, e o que ela escolhe consumir fica cada vez mais perturbador. Tem um significado profundo."),
        ("Se existisse um Little Nightmares 3, o que você gostaria de ver? 🕯️",
         "As possibilidades são enormes! O universo tem tanto pra explorar — a origem de The Maw, outros lugares distorcidos, novos personagens. A comunidade quer muito!",
         "Seria incrível! O universo é rico e misterioso. Novos cenários, novas criaturas e mais da lore de Six fariam um terceiro jogo espetacular. Tomara que aconteça!"),
    ],
}
